global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds.
  evaluation_interval: 5s # Evaluate rules every 5 seconds.

scrape_configs:
  - job_name: 'profile'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'profile:8080' ]
  - job_name: 'event'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'event:8081' ]
  - job_name: 'configserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'configserver:8082' ]
  - job_name: 'gatewayserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'gatewayserver:8084' ]
  - job_name: 'eureka'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'eureka:8083' ]
  